import Header from "component/Header";
import "./globals.css";
import Footer from "component/Footer";
import { ToastContainer } from "node_modules/react-toastify/dist";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
